"""empty message

Revision ID: 1906ea1e4eaf
Revises: c474d96fe70a
Create Date: 2023-12-18 20:28:39.482055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1906ea1e4eaf'
down_revision = 'c474d96fe70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urun_kategori',
    sa.Column('urun_kategori', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urun_musteri',
    sa.Column('urun_kisiselbilgiler', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urun_siparismodeli',
    sa.Column('urun_siparis', sa.String(), nullable=False),
    sa.Column('urun_bilgi', sa.String(), nullable=False),
    sa.Column('urun_adet', sa.Integer(), nullable=False),
    sa.Column('urun_fiyat', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urun_yorum',
    sa.Column('urun_siparis', sa.String(), nullable=False),
    sa.Column('urun_bilgi', sa.String(), nullable=False),
    sa.Column('urun_yorum', sa.String(), nullable=True),
    sa.Column('urun_puan', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urunler',
    sa.Column('urun_kodu', sa.String(), nullable=False),
    sa.Column('urun_adi', sa.String(), nullable=False),
    sa.Column('urun_resim', sa.String(), nullable=True),
    sa.Column('urun_fiyat', sa.Float(), nullable=False),
    sa.Column('urun_aciklama', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urun_kodu')
    )
    op.create_table('urun_siparis',
    sa.Column('urun_tarih', sa.Date(), nullable=False),
    sa.Column('urun_firma', sa.String(), nullable=False),
    sa.Column('urun_musteri', sa.String(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urun_siparis')
    op.drop_table('urunler')
    op.drop_table('urun_yorum')
    op.drop_table('urun_siparismodeli')
    op.drop_table('urun_musteri')
    op.drop_table('urun_kategori')
    # ### end Alembic commands ###
