"""empty message

Revision ID: 2fbd468956f4
Revises: 8c58e81ee651
Create Date: 2023-12-30 19:22:41.783582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbd468956f4'
down_revision = '8c58e81ee651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticaret', schema=None) as batch_op:
        batch_op.alter_column('ticaret_telefon',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticaret', schema=None) as batch_op:
        batch_op.alter_column('ticaret_telefon',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
