"""empty message

Revision ID: 31679adae976
Revises: 1906ea1e4eaf
Create Date: 2023-12-22 23:35:39.374669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31679adae976'
down_revision = '1906ea1e4eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticaret', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False))
        batch_op.drop_column('olusturulma_tarihi')

    with op.batch_alter_table('urun_kategori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False))
        batch_op.drop_column('olusturulma_tarihi')

    with op.batch_alter_table('urun_musteri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False))
        batch_op.drop_column('olusturulma_tarihi')

    with op.batch_alter_table('urun_siparis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False))
        batch_op.drop_column('olusturulma_tarihi')

    with op.batch_alter_table('urun_siparismodeli', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False))
        batch_op.drop_column('olusturulma_tarihi')

    with op.batch_alter_table('urun_yorum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False))
        batch_op.drop_column('olusturulma_tarihi')

    with op.batch_alter_table('urunler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False))
        batch_op.drop_column('olusturulma_tarihi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urunler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olusturulma_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('ekleme_tarihi')

    with op.batch_alter_table('urun_yorum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olusturulma_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('ekleme_tarihi')

    with op.batch_alter_table('urun_siparismodeli', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olusturulma_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('ekleme_tarihi')

    with op.batch_alter_table('urun_siparis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olusturulma_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('ekleme_tarihi')

    with op.batch_alter_table('urun_musteri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olusturulma_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('ekleme_tarihi')

    with op.batch_alter_table('urun_kategori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olusturulma_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('ekleme_tarihi')

    with op.batch_alter_table('ticaret', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olusturulma_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('ekleme_tarihi')

    # ### end Alembic commands ###
