"""empty message

Revision ID: 37a34f882ce7
Revises: 
Create Date: 2023-12-18 19:34:41.088743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a34f882ce7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticaret',
    sa.Column('ticaret_adi', sa.String(), nullable=False),
    sa.Column('ticaret_adres', sa.String(), nullable=True),
    sa.Column('ticaret_yetkiliKisi', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticaret')
    # ### end Alembic commands ###
