"""empty message

Revision ID: c474d96fe70a
Revises: 37a34f882ce7
Create Date: 2023-12-18 19:59:34.854949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c474d96fe70a'
down_revision = '37a34f882ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticaret', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticaret_telefon', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticaret', schema=None) as batch_op:
        batch_op.drop_column('ticaret_telefon')

    # ### end Alembic commands ###
